export const cardWithBingo = [
  { postion: 0, digit: 34, marked: false },
  { postion: 1, digit: 90, marked: false },
  { postion: 2, digit: 18, marked: false },
  { postion: 3, digit: 33, marked: false },
  { postion: 4, digit: 83, marked: false },
  { postion: 5, digit: 27, marked: true },
  { postion: 6, digit: 7, marked: true },
  { postion: 7, digit: 25, marked: true },
  { postion: 8, digit: 61, marked: true },
  { postion: 9, digit: 15, marked: true },
  { postion: 10, digit: 43, marked: false },
  { postion: 11, digit: 5, marked: false },
  { postion: 12, digit: 51, marked: false },
  { postion: 13, digit: 32, marked: false },
  { postion: 14, digit: 45, marked: false },
  { postion: 15, digit: 24, marked: false },
  { postion: 16, digit: 17, marked: false },
  { postion: 17, digit: 72, marked: false },
  { postion: 18, digit: 31, marked: false },
  { postion: 19, digit: 22, marked: false },
  { postion: 20, digit: 77, marked: false },
  { postion: 21, digit: 46, marked: false },
  { postion: 22, digit: 78, marked: false },
  { postion: 23, digit: 16, marked: false },
  { postion: 24, digit: 9, marked: false },
]

export const cardWithoutBingo = [
  { postion: 0, digit: 34, marked: false },
  { postion: 1, digit: 90, marked: false },
  { postion: 2, digit: 18, marked: false },
  { postion: 3, digit: 33, marked: false },
  { postion: 4, digit: 83, marked: false },
  { postion: 5, digit: 27, marked: false },
  { postion: 6, digit: 7, marked: false },
  { postion: 7, digit: 25, marked: false },
  { postion: 8, digit: 61, marked: false },
  { postion: 9, digit: 15, marked: false },
  { postion: 10, digit: 43, marked: false },
  { postion: 11, digit: 5, marked: false },
  { postion: 12, digit: 51, marked: false },
  { postion: 13, digit: 32, marked: false },
  { postion: 14, digit: 45, marked: false },
  { postion: 15, digit: 24, marked: false },
  { postion: 16, digit: 17, marked: false },
  { postion: 17, digit: 72, marked: false },
  { postion: 18, digit: 31, marked: false },
  { postion: 19, digit: 22, marked: false },
  { postion: 20, digit: 77, marked: false },
  { postion: 21, digit: 46, marked: false },
  { postion: 22, digit: 78, marked: false },
  { postion: 23, digit: 16, marked: false },
  { postion: 24, digit: 9, marked: false },
]
